const MATCHING_SYSTEM = {
  FACTORS: {
    DISTANCE_IMPORTANCE: 3,
    DISTANCE_CONSTANT: -0.001,
    INTERESTS_IMPORTANCE: 2,
    INTERESTS_CONSTANT: -1,
    POPULARITY_IMPORTANCE: 2,
  },
  POPULARITY_POINTS: {
    PROFILE_VIEW: 15,
    LIKE: 50,
    UNLIKE: 50,
    BLOCK: 100,
  },
}

const BOUNDARY_VALUES = {
  AGE_MIN: 18,
  AGE_MAX: 99,
  POPULARITY_MIN: 0,
  POPULARITY_MAX: 5000,
}

module.exports = { MATCHING_SYSTEM, BOUNDARY_VALUES }
